POST http://localhost:3001/api/notes
Content-Type: application/json

// Background field optional. Not sending a background
// colour defaults the colour to white (#000000)
{  
    "title": "coinTest1",
    "body": "note notey note",
    "username": "coins",
    "background": "red"
}